---
title: "3. Bond analyses"
author: "Andrei Pazniak"
format: html
editor: visual
---


```{r init, echo=FALSE, include=FALSE}
library(data.table);library(ggplot2);library(plotly)
source("..\\common\\QuotesTransform.R")

data <- fread("cleanedSeries.csv")

targetName <- "TLT"

```

```{r bondyield}
bond <- data[date>'1998-01-01'][series_id=="BAMLH0A0HYM2EY" | series_id=="IRLTLT01USM156N"]
scaleFactor <- 10
d <- data.table(date = unique(bond$date), value = scaleFactor*bond[series_id=="IRLTLT01USM156N", value]/ bond[series_id=="BAMLH0A0HYM2EY", value], series_id = "tlt2junk", type="USA Economic/Percent")
d <- rbind(bond, d, fill=TRUE)
p <- ggplot(d, aes(x=date, y=value, color=series_id))  + geom_line() + geom_hline(yintercept = 2, color="blue") + geom_hline(yintercept = 5, color="blue")
ggplotly(p)

```
```{r tltchart}
p <- ggplot(data[date>'1998-01-01'][series_id==targetName])  + geom_line(aes(x=date, y=adjusted_value_m2), color='blue') +geom_line(aes(x=date, y=value), color='green')
ggplotly(p)
```