---
title: "Seasonality"
author: "Andrei Pazniak"
date: "2/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

source("..\\common\\DownloadQuotes.R")

library(lubridate)
library(zoo)
library(ggplot2)
library(data.table)
library(foreach)
library(tidyquant)
library(PerformanceAnalytics)
```

```{r constants, include=FALSE}
SYMBOL <- "WMB"
START_YEAR <- 2000
END_YEAR <- 2020
WINDOW_SIZE <- 10
CLUSTER_SIZE <- 3
```

## Analyses for symbol `r SYMBOL`
### Download and tranform daily data to relative form openDailyPriceToday / openDailyPriceYesterday
```{r download, echo=FALSE}
GetNormalizeData <- function (symbol = "SBUX", year=2019){
  d <- GetQuotes(symbol, startDate=ISOdate(year, 1, 1, tz = "UTC"), endDate=ISOdate(year+1, 1, 1, tz = "UTC"), periodicity="D1", type="Bids")
  d[,day := lubridate::yday(datetime)]
  d <- d[,.(day, rateOpen=open / shift(open))]
  setkey(d, day)
  d <- d[CJ(1:366)]
  #setnafill(d, type="locf")
  d[is.na(rateOpen), rateOpen := 1]
  d
}
r<- foreach(year=START_YEAR:END_YEAR+1, .combine=rbind) %do% {
  d<-GetNormalizeData(SYMBOL, year)
  d[,year:=year]
  d
}
##ggplot(r, aes(x=day, y=rateOpen, group=year, color=year)) + geom_ma()
ggplot(r, aes(x=year, y=rateOpen, group=year)) + geom_boxplot()
```

### Geom moving average for last `r WINDOW_SIZE` days. 
```{r geometric}
#geom moving average for each year
m <- r[,.(day,mva=frollapply(rateOpen, WINDOW_SIZE, mean.geometric)), by=year]
curr_year <- m[year > END_YEAR]
curr_year[mva==1, mva:=NA]
ggplot(m, aes(x=day, y=mva, group=year, color=year)) + geom_line()
```

### Cluster it with size = `r CLUSTER_SIZE`
```{r}
wide <- dcast(m[year<=END_YEAR], year ~ day, value.var = "mva")
wide_data <- wide[,-1:-WINDOW_SIZE]
means_data <- kmeans(wide_data, CLUSTER_SIZE)

split(wide$year, means_data$cluster)
```
### Plot cluster centers.
```{r fig.width=20, fig.height=15}
centers <- as.data.table(means_data$centers)
centers [,clusterIndex:= seq_len(.N)]
centers[,clusterPower:=means_data$size/sum(means_data$size)]

cTable <- melt(centers, id.vars = c("clusterIndex", "clusterPower"), variable.name ="day", variable.factor = FALSE)
cTable[,day := as.numeric(day) ]
ggplot() + geom_line(data=cTable, aes(x=day, y=value)) + geom_hline(yintercept = 1, color="red") + geom_line(data=curr_year, aes(x=day, y=mva), color="red") + facet_wrap(~clusterIndex,  ncol=1)

```

### Plot geom average for all years 
```{r}
m2 <- m[year <= END_YEAR,.(mva=mean.geometric(mva)), by=day]
m2_curr_year <- m[year > END_YEAR,]
ggplot() + geom_line(data=m2, aes(x=day, y=mva)) + geom_line(data=m2_curr_year, aes(x=day, y=mva), color="red")
```
```{r test}
g <- m2[, is_positive := mva >=1]
g<- g[,.(startDay=first(day), lastDay=last(day), area=sum(mva-1)), by=.(is_positive, rleid(is_positive))]
g[, duration:= lastDay - startDay+1]
g <- g[abs(area) > 0.01,]

first_date <- floor_date(today("GMT"), unit="year")
g[, start:= first_date + startDay-1]
g[, last:= first_date + lastDay-1]
```

### Plot cummulative geom average 
```{r}
m2[is.na(mva), mva:=1]
m2[,cum_mva:= cumprod(mva)]
#m2_curr_year[is.na(mva), mva:=1]
m2_curr_year <- r[year>END_YEAR]
m2_curr_year[,cum_rateOpen:= cumprod(rateOpen )]

ggplot() + geom_line(data=m2, aes(x=day, y=cum_mva)) + geom_line(data=m2_curr_year, aes(x=day, y=cum_rateOpen), color="red")
```